# Copyright (C) 2015 The AOSPERIA Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PRODUCT_COPY_FILES += \
    vendor/sony/tulip/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/sony/tulip/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/sony/tulip/proprietary/lib/libcnefeatureconfig.so:system/lib/libcnefeatureconfig.so \
    vendor/sony/tulip/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    vendor/sony/tulip/proprietary/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so \
    vendor/sony/tulip/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/sony/tulip/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    vendor/sony/tulip/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so \
    vendor/sony/tulip/proprietary/lib/librmnetctl.so:system/lib/librmnetctl.so \
    vendor/sony/tulip/proprietary/lib64/hw/sensors.default.so:system/lib64/hw/sensors.default.so \
    vendor/sony/tulip/proprietary/lib64/libcnefeatureconfig.so:system/lib64/libcnefeatureconfig.so \
    vendor/sony/tulip/proprietary/lib64/libloc_ds_api.so:system/lib64/libloc_ds_api.so \
    vendor/sony/tulip/proprietary/lib64/librmnetctl.so:system/lib64/librmnetctl.so \
    vendor/sony/tulip/proprietary/vendor/bin/audioflacapp:system/vendor/bin/audioflacapp \
    vendor/sony/tulip/proprietary/vendor/bin/slim_ap_daemon:system/vendor/bin/slim_ap_daemon \
    vendor/sony/tulip/proprietary/vendor/bin/sound_trigger_test:system/vendor/bin/sound_trigger_test \
    vendor/sony/tulip/proprietary/vendor/lib/lib-dplmedia.so:system/vendor/lib/lib-dplmedia.so \
    vendor/sony/tulip/proprietary/vendor/lib/lib-imsSDP.so:system/vendor/lib/lib-imsSDP.so \
    vendor/sony/tulip/proprietary/vendor/lib/lib-imscamera.so:system/vendor/lib/lib-imscamera.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera_gt24c16_eeprom.so:system/vendor/lib/libmmcamera_gt24c16_eeprom.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera_hi256.so:system/vendor/lib/libmmcamera_hi256.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera_imx214.so:system/vendor/lib/libmmcamera_imx214.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera_imx214_2nd.so:system/vendor/lib/libmmcamera_imx214_2nd.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera_isp_arcsoft.so:system/vendor/lib/libmmcamera_isp_arcsoft.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera_ov5648_f.so:system/vendor/lib/libmmcamera_ov5648_f.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera_ov5648_f_2nd.so:system/vendor/lib/libmmcamera_ov5648_f_2nd.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmhttpstack.so:system/vendor/lib/libmmhttpstack.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmi.so:system/vendor/lib/libmmi.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmiipstreammmihttp.so:system/vendor/lib/libmmiipstreammmihttp.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmipstreamaal.so:system/vendor/lib/libmmipstreamaal.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmipstreamnetwork.so:system/vendor/lib/libmmipstreamnetwork.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmipstreamsourcehttp.so:system/vendor/lib/libmmipstreamsourcehttp.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmipstreamutils.so:system/vendor/lib/libmmipstreamutils.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmrtpdecoder.so:system/vendor/lib/libmmrtpdecoder.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmrtpencoder.so:system/vendor/lib/libmmrtpencoder.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmwfdinterface.so:system/vendor/lib/libmmwfdinterface.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmwfdsinkinterface.so:system/vendor/lib/libmmwfdsinkinterface.so \
    vendor/sony/tulip/proprietary/vendor/lib/libmmwfdsrcinterface.so:system/vendor/lib/libmmwfdsrcinterface.so \
    vendor/sony/tulip/proprietary/vendor/lib/libnative_audio_latency_jni.so:system/vendor/lib/libnative_audio_latency_jni.so \
    vendor/sony/tulip/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/sony/tulip/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/sony/tulip/proprietary/vendor/lib/liboemcrypto.so:system/vendor/lib/liboemcrypto.so \
    vendor/sony/tulip/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/sony/tulip/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/sony/tulip/proprietary/vendor/lib/libqct_resampler.so:system/vendor/lib/libqct_resampler.so \
    vendor/sony/tulip/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/sony/tulip/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/sony/tulip/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/sony/tulip/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/sony/tulip/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/sony/tulip/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/sony/tulip/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/sony/tulip/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/sony/tulip/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/sony/tulip/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/sony/tulip/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    vendor/sony/tulip/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/sony/tulip/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    vendor/sony/tulip/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
    vendor/sony/tulip/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/sony/tulip/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/sony/tulip/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/sony/tulip/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/sony/tulip/proprietary/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
    vendor/sony/tulip/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/sony/tulip/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/sony/tulip/proprietary/vendor/lib/libscve.so:system/vendor/lib/libscve.so \
    vendor/sony/tulip/proprietary/vendor/lib/libscve_mv.so:system/vendor/lib/libscve_mv.so \
    vendor/sony/tulip/proprietary/vendor/lib/libsd_sdk_display.so:system/vendor/lib/libsd_sdk_display.so \
    vendor/sony/tulip/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    vendor/sony/tulip/proprietary/vendor/lib/libsrsprocessing.so:system/vendor/lib/libsrsprocessing.so \
    vendor/sony/tulip/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    vendor/sony/tulip/proprietary/vendor/lib/libsubsystem_control.so:system/vendor/lib/libsubsystem_control.so \
    vendor/sony/tulip/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    vendor/sony/tulip/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/sony/tulip/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    vendor/sony/tulip/proprietary/vendor/lib/libtzdrmgenprov.so:system/vendor/lib/libtzdrmgenprov.so \
    vendor/sony/tulip/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
    vendor/sony/tulip/proprietary/vendor/lib/libvcel.so:system/vendor/lib/libvcel.so \
    vendor/sony/tulip/proprietary/vendor/lib/libvendorconn.so:system/vendor/lib/libvendorconn.so \
    vendor/sony/tulip/proprietary/vendor/lib/libvoice-svc.so:system/vendor/lib/libvoice-svc.so \
    vendor/sony/tulip/proprietary/vendor/lib/libwfdcommonutils.so:system/vendor/lib/libwfdcommonutils.so \
    vendor/sony/tulip/proprietary/vendor/lib/libwfdmmsink.so:system/vendor/lib/libwfdmmsink.so \
    vendor/sony/tulip/proprietary/vendor/lib/libwfdmmsrc.so:system/vendor/lib/libwfdmmsrc.so \
    vendor/sony/tulip/proprietary/vendor/lib/libwfdmmutils.so:system/vendor/lib/libwfdmmutils.so \
    vendor/sony/tulip/proprietary/vendor/lib/libwfdnative.so:system/vendor/lib/libwfdnative.so \
    vendor/sony/tulip/proprietary/vendor/lib/libwfdrtsp.so:system/vendor/lib/libwfdrtsp.so \
    vendor/sony/tulip/proprietary/vendor/lib/libwfdservice.so:system/vendor/lib/libwfdservice.so \
    vendor/sony/tulip/proprietary/vendor/lib/libwfdsm.so:system/vendor/lib/libwfdsm.so \
    vendor/sony/tulip/proprietary/vendor/lib/libwfduibcinterface.so:system/vendor/lib/libwfduibcinterface.so \
    vendor/sony/tulip/proprietary/vendor/lib/libwfduibcsink.so:system/vendor/lib/libwfduibcsink.so \
    vendor/sony/tulip/proprietary/vendor/lib/libwfduibcsinkinterface.so:system/vendor/lib/libwfduibcsinkinterface.so \
    vendor/sony/tulip/proprietary/vendor/lib/libwfduibcsrc.so:system/vendor/lib/libwfduibcsrc.so \
    vendor/sony/tulip/proprietary/vendor/lib/libwfduibcsrcinterface.so:system/vendor/lib/libwfduibcsrcinterface.so \
    vendor/sony/tulip/proprietary/vendor/lib/libwifiscanner.so:system/vendor/lib/libwifiscanner.so \
    vendor/sony/tulip/proprietary/vendor/lib/libwqe.so:system/vendor/lib/libwqe.so \
    vendor/sony/tulip/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/sony/tulip/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/sony/tulip/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/sony/tulip/proprietary/vendor/lib/libxt_native.so:system/vendor/lib/libxt_native.so \
    vendor/sony/tulip/proprietary/vendor/lib/libxtadapter.so:system/vendor/lib/libxtadapter.so \
    vendor/sony/tulip/proprietary/vendor/lib/libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so \
    vendor/sony/tulip/proprietary/vendor/lib/libxtwifi_zpp_adaptor.so:system/vendor/lib/libxtwifi_zpp_adaptor.so \
    vendor/sony/tulip/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/sony/tulip/proprietary/vendor/lib/mediadrm/libmarlincdmplugin.so:system/vendor/lib/mediadrm/libmarlincdmplugin.so \
    vendor/sony/tulip/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_audio.so:system/vendor/lib/mmi_audio.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_battery.so:system/vendor/lib/mmi_battery.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_bt.so:system/vendor/lib/mmi_bt.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_flashlight.so:system/vendor/lib/mmi_flashlight.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_fm.so:system/vendor/lib/mmi_fm.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_gps_garden.so:system/vendor/lib/mmi_gps_garden.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_gsensor.so:system/vendor/lib/mmi_gsensor.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_gyroscope.so:system/vendor/lib/mmi_gyroscope.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_key.so:system/vendor/lib/mmi_key.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_keypadbacklight.so:system/vendor/lib/mmi_keypadbacklight.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_lcd.so:system/vendor/lib/mmi_lcd.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_led.so:system/vendor/lib/mmi_led.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_lsensor.so:system/vendor/lib/mmi_lsensor.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_msensor.so:system/vendor/lib/mmi_msensor.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_nfc.so:system/vendor/lib/mmi_nfc.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_psensor.so:system/vendor/lib/mmi_psensor.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_sdcard.so:system/vendor/lib/mmi_sdcard.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_sim.so:system/vendor/lib/mmi_sim.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_sysinfo.so:system/vendor/lib/mmi_sysinfo.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_touch.so:system/vendor/lib/mmi_touch.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_touchpanel.so:system/vendor/lib/mmi_touchpanel.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_vibrator.so:system/vendor/lib/mmi_vibrator.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_volume.so:system/vendor/lib/mmi_volume.so \
    vendor/sony/tulip/proprietary/vendor/lib/mmi_wifi.so:system/vendor/lib/mmi_wifi.so \
    vendor/sony/tulip/proprietary/vendor/lib64/libmmcamera2_frame_algorithm.so:system/vendor/lib64/libmmcamera2_frame_algorithm.so \
    vendor/sony/tulip/proprietary/vendor/lib64/libmmcamera2_stats_algorithm.so:system/vendor/lib64/libmmcamera2_stats_algorithm.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_audio.so:system/vendor/lib64/mmi_audio.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_battery.so:system/vendor/lib64/mmi_battery.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_bt.so:system/vendor/lib64/mmi_bt.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_flashlight.so:system/vendor/lib64/mmi_flashlight.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_fm.so:system/vendor/lib64/mmi_fm.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_gps_garden.so:system/vendor/lib64/mmi_gps_garden.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_gsensor.so:system/vendor/lib64/mmi_gsensor.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_gyroscope.so:system/vendor/lib64/mmi_gyroscope.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_key.so:system/vendor/lib64/mmi_key.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_keypadbacklight.so:system/vendor/lib64/mmi_keypadbacklight.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_lcd.so:system/vendor/lib64/mmi_lcd.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_led.so:system/vendor/lib64/mmi_led.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_lsensor.so:system/vendor/lib64/mmi_lsensor.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_msensor.so:system/vendor/lib64/mmi_msensor.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_nfc.so:system/vendor/lib64/mmi_nfc.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_psensor.so:system/vendor/lib64/mmi_psensor.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_sdcard.so:system/vendor/lib64/mmi_sdcard.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_sim.so:system/vendor/lib64/mmi_sim.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_sysinfo.so:system/vendor/lib64/mmi_sysinfo.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_touch.so:system/vendor/lib64/mmi_touch.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_touchpanel.so:system/vendor/lib64/mmi_touchpanel.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_vibrator.so:system/vendor/lib64/mmi_vibrator.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_volume.so:system/vendor/lib64/mmi_volume.so \
    vendor/sony/tulip/proprietary/vendor/lib64/mmi_wifi.so:system/vendor/lib64/mmi_wifi.so 